language = "C"
tab_width = 2
include_guard = "DDTRACE_PHP_H"
style = "both"
header = """
struct _zend_string;
"""

no_includes = true
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]
includes = ["common.h", "telemetry.h", "sidecar.h"]

[export]
prefix = "ddog_"
renaming_overrides_prefixing = true

[export.mangle]
rename_types = "PascalCase"

[export.rename]
"ParseTagsResult" = "ddog_Vec_Tag_ParseResult"
"PushTagResult" = "ddog_Vec_Tag_PushResult"
"ZendString" = "_zend_string"
"FILE" = "FILE"

[enum]
prefix_with_name = true
rename_variants = "ScreamingSnakeCase"

[parse]
parse_deps = true
include = [
    "libdd-common",
    "libdd-telemetry",
    "libdd-telemetry-ffi",
    "libdd-common-ffi",
    "datadog-crashtracker-ffi",
    "datadog-sidecar",
    "datadog-ipc",
    "datadog-live-debugger",
    "datadog-live-debugger-ffi",
    "datadog-remote-config",
    "uuid"
]
