language = "C"
tab_width = 2
include_guard = "DDTRACE_PHP_H"
style = "both"

no_includes = true
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]
includes = ["common.h", "telemetry.h", "sidecar.h"]

[export]
prefix = "ddog_"
renaming_overrides_prefixing = true

[export.mangle]
rename_types = "PascalCase"

[export.rename]
"ParseTagsResult" = "ddog_Vec_Tag_ParseResult"
"PushTagResult" = "ddog_Vec_Tag_PushResult"
"FILE" = "FILE"

[enum]
prefix_with_name = true
rename_variants = "ScreamingSnakeCase"

[parse]
parse_deps = true
include = ["ddcommon", "ddtelemetry", "ddcommon-ffi", "ddtelemetry-ffi", "datadog-profiling-ffi", "datadog-sidecar", "datadog-ipc", "uuid"]
