version: '3.7'

services:

  base:
    image: datadog/dd-trace-ci:bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      x-bake: &bake
        platforms:
          - linux/arm64
          - linux/amd64
      args: &build-base
        BUILD_BASE: datadog/dd-trace-ci:bookworm-$BOOKWORM_NEXT_VERSION

  php-8.4:
    image: datadog/dd-trace-ci:php-8.4_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-8.4/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "8.4"
        phpTarGzUrl: https://downloads.php.net/~saki/php-8.4.0RC1.tar.gz
        phpSha256Hash: "ff924ce24493cd546c7227c2cedf75c32d23815b0a6e5c1658d9b005837631ff"

  php-8.3:
    image: datadog/dd-trace-ci:php-8.3_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-8.3/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "8.3"
        phpTarGzUrl: https://www.php.net/distributions/php-8.3.9.tar.gz
        phpSha256Hash: "f484dec6ee005c83f899af02fc021e1bc3b1d7b3f143ca062ef66b0fcee96566"

  php-8.2:
    image: datadog/dd-trace-ci:php-8.2_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-8.2/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "8.2"
        phpTarGzUrl: https://www.php.net/distributions/php-8.2.21.tar.gz
        phpSha256Hash: "0c6323699309a4d2e71057f01bc071b199f240973c349287b667a3ab36a496c6"

  php-8.1:
    image: datadog/dd-trace-ci:php-8.1_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-8.1/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "8.1"
        phpTarGzUrl: https://www.php.net/distributions/php-8.1.29.tar.gz
        phpSha256Hash: "8b2609bf1d3173aa38269a9af21532c65f730aadd3051f9aae011eea9e246de5"

  php-8.0:
    image: datadog/dd-trace-ci:php-8.0_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-8.0/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "8.0"
        phpTarGzUrl: https://www.php.net/distributions/php-8.0.30.tar.gz
        phpSha256Hash: "449d2048fcb20a314d8c218097c6d1047a9f1c5bb72aa54d5d3eba0a27a4c80c"

  php-8.0-shared-ext:
    image: datadog/dd-trace-ci:php-8.0-shared-ext-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-8.0/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        sharedBuild: 1
        phpVersion: "8.0"
        phpTarGzUrl: https://www.php.net/distributions/php-8.0.30.tar.gz
        phpSha256Hash: "449d2048fcb20a314d8c218097c6d1047a9f1c5bb72aa54d5d3eba0a27a4c80c"

  php-7.4:
    image: datadog/dd-trace-ci:php-7.4_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-7.4/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "7.4"
        phpTarGzUrl: https://www.php.net/distributions/php-7.4.33.tar.gz
        phpSha256Hash: 5a2337996f07c8a097e03d46263b5c98d2c8e355227756351421003bea8f463e

  php-7.4-shared-ext:
    image: datadog/dd-trace-ci:php-7.4-shared-ext-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-7.4/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        sharedBuild: 1
        phpVersion: "7.4"
        phpTarGzUrl: https://www.php.net/distributions/php-7.4.33.tar.gz
        phpSha256Hash: 5a2337996f07c8a097e03d46263b5c98d2c8e355227756351421003bea8f463e

  php-7.3:
    image: datadog/dd-trace-ci:php-7.3_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-7.3/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "7.3"
        phpTarGzUrl: https://www.php.net/distributions/php-7.3.33.tar.gz
        phpSha256Hash: 9a369c32c6f52036b0a890f290327f148a1904ee66aa56e2c9a7546da6525ec8

  php-7.2:
    image: datadog/dd-trace-ci:php-7.2_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-7.2/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "7.2"
        phpTarGzUrl: https://www.php.net/distributions/php-7.2.34.tar.gz
        phpSha256Hash: 8b2777c741e83f188d3ca6d8e98ece7264acafee86787298fae57e05d0dddc78

  php-7.1:
    image: datadog/dd-trace-ci:php-7.1_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-7.1/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "7.1"
        phpTarGzUrl: https://www.php.net/distributions/php-7.1.33.tar.gz
        phpSha256Hash: 0055f368ffefe51d5a4483755bd17475e88e74302c08b727952831c5b2682ea2

  php-7.0:
    image: datadog/dd-trace-ci:php-7.0_bookworm-$BOOKWORM_NEXT_VERSION
    build:
      context: .
      dockerfile: php-7.0/Dockerfile
      x-bake: *bake
      args:
        <<: *build-base
        phpVersion: "7.0"
        phpTarGzUrl: https://www.php.net/distributions/php-7.0.33.tar.gz
        phpSha256Hash: d71a6ecb6b13dc53fed7532a7f8f949c4044806f067502f8fb6f9facbb40452a

