version: '3.2'

services:
  '5.4-centos6': &base_image
    ulimits: { core: 99999999999 }
    stdin_open: true
    tty: true
    volumes: [ '../../:/build_src' ]
    cap_add: [ SYS_PTRACE ]
    image: 'datadog/docker-library:ddtrace_centos_6_php_5_4'
  '5.5-centos6':
    <<: *base_image
    image: 'datadog/dd-trace-ci:php-5.5_centos-6'
    environment:
      - BASH_ENV=/etc/profile.d/zzz-ddtrace.sh
  '5.6-centos6': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_6_php_56' }
  '7.0-centos6': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_6_php_70' }
  '7.1-centos6': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_6_php_71' }
  '7.2-centos6': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_6_php_72' }
  '5.4-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_54' }
  '5.6-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_56' }
  '7.0-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_70' }
  '7.1-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_71' }
  '7.2-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_72' }
  '7.3-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_73' }
  '7.4-centos7': { <<: *base_image, image: 'datadog/dd-trace-ci:php-7.4-centos-7' }

  alpine:
    image: ${ALPINE_IMAGE}
    working_dir: /datadog
    volumes:
      - ../../:/datadog
    environment:
      PHP_PACKAGE: ${PHP_PACKAGE}
      PACKAGE_TYPE: ${PACKAGE_TYPE}
    depends_on:
      - request-replayer

  request-replayer:
    image: datadog/dd-trace-ci:php-request-replayer
