version: '3.2'

services:
  '5.6-centos6': &base_image
    ulimits: { core: 99999999999 }
    stdin_open: true
    tty: true
    volumes: [ '../../:/build_src' ]
    cap_add: [ SYS_PTRACE ]
    image: 'datadog/docker-library:ddtrace_centos_6_php_56'
  '7.0-centos6': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_6_php_70' }
  '7.1-centos6': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_6_php_71' }
  '7.2-centos6': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_6_php_72' }
  '5.4-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_54' }
  '5.6-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_56' }
  '7.0-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_70' }
  '7.1-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_71' }
  '7.2-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_72' }
  '7.3-centos7': { <<: *base_image, image: 'datadog/docker-library:ddtrace_centos_7_php_73' }
  '7.4-centos7': { <<: *base_image, image: 'datadog/dd-trace-ci:php-7.4-centos-7' }
  '5.6-alpine':  { <<: *base_image, image: 'php:5.6-alpine' }
  '7.0-alpine':  { <<: *base_image, image: 'php:7.0-alpine' }
  '7.1-alpine':  { <<: *base_image, image: 'php:7.1-alpine' }
  '7.2-alpine':  { <<: *base_image, image: 'php:7.2-alpine' }
  '7.3-alpine':  { <<: *base_image, image: 'php:7.3-alpine' }
  '7.4-alpine':  { <<: *base_image, image: 'php:7.4-alpine' }
  '5.6-zts-alpine':  { <<: *base_image, image: 'php:5.6-zts-alpine' }
  '7.0-zts-alpine':  { <<: *base_image, image: 'php:7.0-zts-alpine' }
  '7.1-zts-alpine':  { <<: *base_image, image: 'php:7.1-zts-alpine' }
  '7.2-zts-alpine':  { <<: *base_image, image: 'php:7.2-zts-alpine' }
  '7.3-zts-alpine':  { <<: *base_image, image: 'php:7.3-zts-alpine' }
  '7.4-zts-alpine':  { <<: *base_image, image: 'php:7.4-zts-alpine' }
