version: "3.7"

services:

  "7.3":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-laravel:7.3"
    depends_on:
      - agent
    ports:
      - 7777:80
    environment:
      - DD_AGENT_HOST=agent
      - TRACER_DOWNLOAD_URL=https://github.com/DataDog/dd-trace-php/releases/download/0.51.0/datadog-php-tracer_0.51.0_amd64.deb
      - DD_SERVICE=laravel57-php73-synthetic
      # - DD_TRACE_DEBUG=true
    # volumes:
    #   - ./57:/var/www/html/
    command: [ "/scripts/local-run.sh" ]

  "8.0":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-laravel:8.0"
    depends_on:
      - agent
    ports:
      - 7778:80
    environment:
      - DD_AGENT_HOST=agent
      - TRACER_DOWNLOAD_URL=https://github.com/DataDog/dd-trace-php/releases/download/0.51.0/datadog-php-tracer_0.51.0_amd64.deb
      - DD_SERVICE=laravel8x-php80-synthetic
      # - DD_TRACE_DEBUG=true
    # volumes:
    #   - ./8x:/var/www/html/
    command: [ "/scripts/local-run.sh" ]

  agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_ENV=testenv
