version: '3.7'

services:

  vc14-base:
    image: datadog/dd-trace-ci:windows-base-vc14
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: vc14.Dockerfile

  vc15-base:
    image: datadog/dd-trace-ci:windows-base-vc15
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: vc15.Dockerfile

  vs16-base:
    image: datadog/dd-trace-ci:windows-base-vs16
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: vs16.Dockerfile

  vs17-base:
    image: datadog/dd-trace-ci:windows-base-vs17
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: vs17.Dockerfile

  vc14:
    image: datadog/dd-trace-ci:windows-vc14
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: basetools.Dockerfile
      args:
        vsVersion: "vc14"
        sdkVersion: "2.1.10"

  vc15:
    image: datadog/dd-trace-ci:windows-vc15
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: basetools.Dockerfile
      args:
        vsVersion: "vc15"
        sdkVersion: "2.2.0"

  vs16:
    image: datadog/dd-trace-ci:windows-vs16
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: basetools.Dockerfile
      args:
        vsVersion: "vs16"
        sdkVersion: "2.2.0"

  vs17:
    image: datadog/dd-trace-ci:windows-vs17
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: basetools.Dockerfile
      args:
        vsVersion: "vs17"
        sdkVersion: "2.3.0"

  php-8.5:
    image: datadog/dd-trace-ci:php-8.5_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.5.0"
        vsVersion: "vs17"
        phpTarGzUrl: https://downloads.php.net/~daniels/php-8.5.0RC3.tar.gz
        phpSha256Hash: "937e544d72ee1eb28d2190cadaadf8e5e8d7d8c365b5c1f6a99b4f979a1f3a1b"

  php-8.4:
    image: datadog/dd-trace-ci:php-8.4_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.4.1"
        vsVersion: "vs17"
        phpTarGzUrl: https://www.php.net/distributions/php-8.4.1.tar.gz
        phpSha256Hash: "c3d1ce4157463ea43004289c01172deb54ce9c5894d8722f4e805461bf9feaec"

  php-8.3:
    image: datadog/dd-trace-ci:php-8.3_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.3.9"
        vsVersion: "vs16"
        phpTarGzUrl: https://www.php.net/distributions/php-8.3.9.tar.gz
        phpSha256Hash: "f484dec6ee005c83f899af02fc021e1bc3b1d7b3f143ca062ef66b0fcee96566"

  php-8.2:
    image: datadog/dd-trace-ci:php-8.2_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.2.21"
        vsVersion: "vs16"
        phpTarGzUrl: https://www.php.net/distributions/php-8.2.21.tar.gz
        phpSha256Hash: "0c6323699309a4d2e71057f01bc071b199f240973c349287b667a3ab36a496c6"

  php-8.1:
    image: datadog/dd-trace-ci:php-8.1_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.1.29"
        vsVersion: "vs16"
        phpTarGzUrl: https://www.php.net/distributions/php-8.1.29.tar.gz
        phpSha256Hash: "8b2609bf1d3173aa38269a9af21532c65f730aadd3051f9aae011eea9e246de5"

  php-8.0:
    image: datadog/dd-trace-ci:php-8.0_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.0.28"
        vsVersion: "vs16"
        phpTarGzUrl: https://www.php.net/distributions/php-8.0.28.tar.gz
        phpSha256Hash: "7432184eae01e4e8e39f03f80e8ec0ca2c8bfebc56e9a7b983541ca8805df22f"

  php-7.4:
    image: datadog/dd-trace-ci:php-7.4_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "7.4.33"
        vsVersion: "vc15"
        phpTarGzUrl: https://www.php.net/distributions/php-7.4.33.tar.gz
        phpSha256Hash: 5a2337996f07c8a097e03d46263b5c98d2c8e355227756351421003bea8f463e

  php-7.3:
    image: datadog/dd-trace-ci:php-7.3_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "7.3.33"
        vsVersion: "vc15"
        phpTarGzUrl: https://www.php.net/distributions/php-7.3.33.tar.gz
        phpSha256Hash: 9a369c32c6f52036b0a890f290327f148a1904ee66aa56e2c9a7546da6525ec8

  php-7.2:
    image: datadog/dd-trace-ci:php-7.2_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "7.2.34"
        vsVersion: "vc15"
        phpTarGzUrl: https://www.php.net/distributions/php-7.2.34.tar.gz
        phpSha256Hash: 8b2777c741e83f188d3ca6d8e98ece7264acafee86787298fae57e05d0dddc78

  php-7.1:
    image: datadog/dd-trace-ci:php-7.1_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "7.1.33"
        vsVersion: "vc14"
        phpTarGzUrl: https://www.php.net/distributions/php-7.1.33.tar.gz
        phpSha256Hash: 0055f368ffefe51d5a4483755bd17475e88e74302c08b727952831c5b2682ea2

  php-7.0:
    image: datadog/dd-trace-ci:php-7.0_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "7.0.33"
        vsVersion: "vc14"
        phpTarGzUrl: https://www.php.net/distributions/php-7.0.33.tar.gz
        phpSha256Hash: d71a6ecb6b13dc53fed7532a7f8f949c4044806f067502f8fb6f9facbb40452a
