[package]
edition = "2021"
name = "php_sidecar_mockgen"
version = "0.1.0"

[dependencies]
ddcommon = { path = "../../libdatadog/ddcommon" }
current_platform = "0.2.0"
sidecar_mockgen = { path = "../../libdatadog/tools/sidecar_mockgen" }

[[bin]]
name = "php_sidecar_mockgen"
