name: Integration

on:
  push:
    branches:
      - master
      - develop
      - dd-appsec-php-**
    tags:
      - "*"
  pull_request:
    paths-ignore:
      - 'LICENSE**'
      - NOTICE
      - '**.md'
  schedule:
    - cron:  30 0 * * *
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - version: '7.0-release'
          - version: '7.0-release-zts'
          - version: '7.1-release'
          - version: '7.1-release-zts'
          - version: '7.2-release'
          - version: '7.2-release-zts'
          - version: '7.3-release'
          - version: '7.3-release-zts'
          - version: '7.4-release'
          - version: '7.4-release-zts'
          - version: '8.0-release'
          - version: '8.0-release-zts'
          - version: '8.1-release'
          - version: '8.1-release-zts'
          - version: '8.2.0RC6-release'
          - version: '8.2.0RC6-release-zts'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Cache Gradle artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Pull images
        run: |
          docker pull datadog/dd-appsec-php-ci:toolchain
          docker pull datadog/dd-appsec-php-ci:hunter-cache
          docker pull datadog/dd-appsec-php-ci:php-${{ matrix.cfg.version }}
      - name: Run tests
        run: |
          cd tests/integration
          TERM=dumb ./gradlew --info --scan \
            test${{ matrix.cfg.version }}
